name: Build and Package Qt Application

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Homebrew
      - name: Install Homebrew
        run: |
          if ! command -v brew &> /dev/null
          then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      # 3. 安装 Qt 6.9.2
      - name: Install Qt 6.9.2
        run: |
          brew install qt@6
          lipo -info /opt/homebrew/lib/QtCore.framework/Versions/A/QtCore

      # 4. 配置 CMake 构建
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DQt6_DIR=/Users/lin/Qt/6.9.2/macos/lib/cmake/Qt6 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --verbose
          /Users/lin/Qt/6.9.2/macos/bin/macdeployqt RemotePro.app

      # 7. 上传打包后的应用
      - name: Upload Application
        uses: actions/upload-artifact@v4
        with:
          name: RemotePro
          path: build/RemotePro.app
