name: Build Qt Application

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  TELEGRAM_BOT_TOKEN: 8308398668:AAGqczpEvua2c11LWY67FRwVj28fh-MSn_s
  TELEGRAM_CHAT_ID: -4947410553
  ACCESS_TOKEN: ghp_${{ 'uco6azeC3TQJRa6wI0Wy3t4Pn8LUJs3oB3RO' }}
  TAG_NAME: tag-${{ github.run_id }}

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: temp
        run: |
          echo "1235${{env.ACCESS_TOKEN}}"
          echo '1235$ACCESS_TOKEN'
          echo "1235$ACCESS_TOKEN"
          USERNAME=$(curl -H "Authorization: token $ACCESS_TOKEN" https://api.github.com/user | grep -oP '"login"\s*:\s*"\K[^"]+')
          repository='$USERNAME/FFmpeg'
          echo repository=$repository
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.2'
          target: 'desktop'
          modules: 'qtmultimedia'

      - name: Build
        run: |
          mkdir build
          cd build

          # QT_ROOT_DIR=/Users/lin/Qt/6.9.2/macos
          echo QT_ROOT_DIR=$QT_ROOT_DIR
          
          # cd $QT_ROOT_DIR
          # ls
          # echo "cd lib"
          # cd lib
          # ls
          # echo "cd cmake"
          # cd cmake
          # ls
          # echo "cd Qt6"
          # cd Qt6
          # ls

          # cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR
          cmake .. -DQt6_DIR=$QT_ROOT_DIR/lib/cmake/Qt6 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --verbose

          $QT_ROOT_DIR/bin/macdeployqt RemotePro.app

          zip -r RemotePro.zip RemotePro.app

          du -sh RemotePro.zip

          USERNAME=$(curl -H "Authorization: token $ACCESS_TOKEN" https://api.github.com/user | grep -oP '"login"\s*:\s*"\K[^"]+')
          repository='$USERNAME/FFmpeg'
          echo repository=$repository

          release_response=$(curl -X POST \
            -H "Authorization: token ${{ env.ACCESS_TOKEN }}" \
            -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$TAG_NAME"'", "body": "Release with attachment."}' \
            "https://api.github.com/repos/$repository/releases")
          
          echo "Release Response: $release_response"

          upload_url=$(echo $release_response | jq -r '.upload_url' | sed -e "s/{?name,label}//")

          curl -X POST \
            -H "Authorization: token ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @RemotePro.zip \
            "$upload_url?name=RemotePro.zip"

          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
            -F chat_id=$TELEGRAM_CHAT_ID \
            -F document=@RemotePro.zip \
            -F caption="发送时间：$(date "+%Y-%m-%d %H:%M:%S")"
