name: Build and Package Qt Application

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Homebrew
      - name: Install Homebrew
        run: |
          if ! command -v brew &> /dev/null
          then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      # 3. 安装 Qt 6.9.2
      - name: Install Qt 6.9.2
        run: |
          brew install qt@6
          brew link --force qt@6
          lipo -info /opt/homebrew/lib/QtCore.framework/Versions/A/QtCore

      # 4. 安装 CMake
      - name: Install CMake
        run: |
          brew install cmake

      # 5. 配置 CMake 构建
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      # 6. 编译项目
      - name: Build project
        run: |
          cd build
          cmake --build . --verbose

      # 7. 打包项目
      - name: Package Application
        run: |
          cd build
          macdeployqt RemotePro.app

      # 8. 上传打包后的应用
      - name: Upload Application
        uses: actions/upload-artifact@v4
        with:
          name: RemotePro
          path: build/RemotePro.app
