name: Build Qt Application

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  TELEGRAM_BOT_TOKEN: 8308398668:AAGqczpEvua2c11LWY67FRwVj28fh-MSn_s
  TELEGRAM_CHAT_ID: -4947410553

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 6
        run: |
          brew install qt@6

      - name: Build
        run: |
          mkdir build
          cd build

          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --verbose
          macdeployqt RemotePro.app

          zip -r RemotePro.zip RemotePro.app

          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
            -F chat_id=$TELEGRAM_CHAT_ID \
            -F document=@RemotePro.zip \
            -F caption="文件发送时间：$(date "+%Y-%m-%d %H:%M:%S")"
